variable "tenant" {}
variable "name" {}
variable "environment" {}
variable "vpc_id" {}
variable "cidr_block" {}
variable "pvt_subnet_ids" {}
variable "eks_subnet_ids" {}
variable "additional_ips" {}
variable "eks_version" {}
variable "vpccni_version" {}
variable "coredns_version" {}
variable "kubeproxy_version" {}
variable "ebscsi_version" {}
variable "enable_aws_cicd" {}
variable "fargate_profile" {}
variable "main_capacity_type" {}
variable "main_ami_type" {}
variable "main_disk_size" {}
variable "main_instance_types" {}
variable "main_scaling_config" {}
variable "extra_nodes_deploy" {}
variable "extra_capacity_type" {}
variable "extra_ami_type" {}
variable "extra_disk_size" {}
variable "extra_instance_types" {}
variable "extra_scaling_config" {}
variable "tmp_nodes_deploy" {}
variable "tmp_capacity_type" {}
variable "tmp_ami_type" {}
variable "tmp_disk_size" {}
variable "tmp_instance_types" {}
variable "tmp_scaling_config" {}